name: GitHubActions1

on: 
  push:
    branches:
    - develop
    
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Testing job" 



  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Deploy job" 
