name: GitHubActions1

on: 
  push:
    branches:
    - develop
    
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Testing job" 
    - name: Git clone Repo
      uses: actions/checkout@v1
    - name: List curent folder
      run: ls -la
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print Hello Message
    run : echo "Hello World from Deploy job" 
    
    - name: AWS Version
     run: aws --version
     
    - name: zip available
     run: zip
