name: GitHubActions1
env: 
  DEPLOY_PACKAGE_NAME : "Playbook_ansible_and_resume_${{ github.sha }}.zip"

on: 
  push:
    branches:
    - develop
    
jobs:
  clone_and_zip_repo:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Git clone Repo
      uses: actions/checkout@v1
      
    - name: List curent folder
      run: ls -la
      
    - name: Create ZIP package Repo
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        
    - name: Install npm dependencies
      run: npm install
      
    - name: Run build task
      run: npm run build --if-present
      
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "${{ env.DEPLOY_PACKAGE_NAME }}"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
   #      TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
