name: GitHubActions1
env: 
  DEPLOY_PACKAGE_NAME : "Playbook_ansible_and_resume_${{ github.sha }}.zip"

on: 
  push:
    branches:
    - develop
    
jobs:
  clone_and_zip_repo:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Git clone Repo
      uses: actions/checkout@v1
      
    - name: Create ZIP package Repo
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: List curent folder
      run: ls -la
      
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "${{ env.DEPLOY_PACKAGE_NAME }}"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
