name: GitHubActions1
env: 
  DEPLOY_PACKAGE_NAME : "Playbook_ansible_and_resume_${{ github.sha }}.zip"

on: 
  push:
    branches:
    - develop
    
jobs:
  clone_and_zip_repo:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: List curent folder
      run: ls -la
    
    - name: Git clone Repo
      uses: actions/checkout@v1
      
    - name: List curent folder
      run: ls -la
      
    - name: Create ZIP package Repo
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: List curent folder
      run: ls -la
      
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      
    - name: AWS Version
      run: aws --version
     
    - name: zip available
      run: zip --version
